name: Merge and Build Release
env:
  flutter_version: "1.22.6"

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  BUILD_RELEASE:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: actions/cache@v2
        name: Cache pub dependencies
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}

      - run: flutter pub get
      - run: flutter test

      - uses: actions/checkout@v2
        name: Checkout code

      - name: Extract release tag
        # Extract version tag from commit. eg "bump version to v0.0.0"
        run: |
          envTag=`perl -nle 'm/(v?[0-9.]\d*(-?)([a-z0-9.-]+)*)/g; print $1' <<< '${{ github.head_ref }}'`
          export tag=$envTag
          echo "RELEASE_TAG=$tag" >> $GITHUB_ENV

      - uses: actions/create-release@v1
        name: Create Tag and Release ${{ env.RELEASE_TAG}}
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG}}
          release_name: ${{ env.RELEASE_TAG}}
          draft: false
          prerelease: false

      - uses: dawidd6/action-delete-branch@v3
        name: Delete ${{ env.RELEASE_TAG}} branch
        with:
          github_token: ${{ github.token }}
          branches: ${{ env.RELEASE_TAG}}

      - name: Build the APK
        run: flutter build appbundle --release

      - name: Upload artifact to Github
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/bundle/release/app-release.aab
