name: Create Release and Tag
env:
  flutter_version: "1.22.6"
  main_branch: "main"

on:
  push:
    branches: [active]

jobs:
  create_codebase_release:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'bump version to')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - id: get-tag-name
        name: Extract tag from commit message - "${{ github.event.head_commit.message }}"
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.head_commit.message }}
          regex: /v[0-9.]\d*(-?)([a-z0-9.-]+)*/g

      - name: Assign the tag to env.RELEASE_TAG
        run: |
          echo "RELEASE_TAG=${{ steps.get-tag-name.outputs.match }}" >> $GITHUB_ENV
      
      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}

      - run: flutter pub get
      - run: flutter test

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.RELEASE_TAG}}

      - name: Create Tag and Release ${{ env.RELEASE_TAG}}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG}}
          release_name: ${{ env.RELEASE_TAG}}
          draft: false
          prerelease: false

      - name: Merge ${{ env.RELEASE_TAG}} into ${{ env.main_branch }} branch
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: ${{ env.RELEASE_TAG}}
          target_branch: ${{ env.main_branch }}
          github_token: ${{ github.token }}

      - name: Delete ${{ env.RELEASE_TAG}} branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ github.token }}
          branches: ${{ env.RELEASE_TAG}}
