# This is a basic workflow to help you get started with Actions

name: create release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
env:
  flutter_version: "1.22.6"
  main_branch: "main"

on:
  #   push:
  #     branches: [ develop ]
  create:
    branches:
      - "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      # - uses: webfactory/ssh-agent@v0.4.1
      # with:
      #   ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - uses: subosito/flutter-action@v1
        with:
          flutter_version: ${{ env.flutter_version }}

      - run: flutter pub get
      - run: flutter test

      - name: Checkout code
        uses: actions/checkout@v2

      - id: get-tag-name
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const tag = context.ref.split('/')[2]
            core.setOutput('tag', tag)

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get-tag-name.outputs.tag }}
          release_name: ${{ steps.get-tag-name.outputs.tag }}
          # body: |
          #   Changes in this Release
          #   - First Change
          #   - Second Change
          draft: false
          prerelease: false

      - name: Merge ${{ steps.get-tag-name.outputs.tag }} into ${{ main_branch }} branch
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: ${{ steps.get-tag-name.outputs.tag }}
          target_branch: ${{ main_branch }}
          github_token: ${{ github.token }}

      - name: Delete ${{ steps.get-tag-name.outputs.tag }} branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ github.token }}
          branches: ${{ steps.get-tag-name.outputs.tag }}
