name: Create Release and Tag
env:
  flutter_version: "1.22.6"
  main_branch: "main"

on:
  push:
    branches: [active]

jobs:
  create_codebase_release:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'bump version to')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup release information
        run: |
          envTag=`perl -nle 'm/(v?[0-9.]\d*(-?)([a-z0-9.-]+)*)/g; print $1' <<< ${{ github.event.head_commit.message }}`
          export tag=$envTag
          echo "RELEASE_TAG=$tag" >> $GITHUB_ENV

      # - name: Assign the tag to env.RELEASE_TAG
      #   run: |
      #     echo "RELEASE_TAG=${{ steps.get-tag-name.outputs.result }}" >> $GITHUB_ENV

      - uses: actions/cache@v2
        name: Cache pub dependencies
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}

      - run: flutter pub get
      - run: flutter test

      - uses: actions/checkout@v2
        name: Checkout code

      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.RELEASE_TAG}}

      - uses: actions/create-release@v1
        name: Create Tag and Release ${{ env.RELEASE_TAG}}
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG}}
          release_name: ${{ env.RELEASE_TAG}}
          draft: false
          prerelease: false

      - uses: devmasx/merge-branch@v1.3.1
        name: Merge ${{ env.RELEASE_TAG}} into ${{ env.main_branch }} branch
        with:
          type: now
          from_branch: ${{ env.RELEASE_TAG}}
          target_branch: ${{ env.main_branch }}
          github_token: ${{ github.token }}

      - uses: dawidd6/action-delete-branch@v3
        name: Delete ${{ env.RELEASE_TAG}} branch
        with:
          github_token: ${{ github.token }}
          branches: ${{ env.RELEASE_TAG}}
